fragment EditionInfo on editions {
  id
  title
  subtitle
  asin
  isbn_13
  edition_format
  pages
  audio_seconds
  language {
    code3
  }
  publisher {
    name
  }
  release_date
  audio_seconds
  physical_format
  physical_information
  edition_information
  users_read_count
  book_id
  score
}

fragment Contributions on contributions {
  contribution
  author {
    ...AuthorInfo
  }
}

fragment DefaultEditions on books {
  id

  contributions {
    ...Contributions
  }

  default_audio_edition {
    id
    book_id
    contributions {
      ...Contributions
    }
  }
  default_physical_edition {
    id
    book_id
    contributions {
      ...Contributions
    }
  }
  default_cover_edition {
    id
    book_id
    contributions {
      ...Contributions
    }
  }
  default_ebook_edition {
    id
    book_id
    contributions {
      ...Contributions
    }
  }

  fallback: editions(
    order_by: [
      { score: desc_nulls_last }
      { users_read_count: desc }
      { id: asc }
    ]
    limit: 1
  ) {
    id
    book_id
    contributions {
      ...Contributions
    }
  }
}

fragment WorkInfo on books {
  id
  title
  subtitle
  description
  release_date
  cached_tags(path: "$.Genre")
  cached_image(path: "url")
  slug
  state
  canonical_id
  book_series {
    position
    series {
      id
      name
      description
    }
  }
  rating
  ratings_count
  ...DefaultEditions
}

fragment AuthorInfo on authors {
  id
  name
  slug
  bio
  cached_image(path: "url")
}

query GetWork($bookID: Int!) {
  books_by_pk(id: $bookID) {
    ...WorkInfo
    editions(order_by: { score: desc_nulls_last }) {
      ...EditionInfo
    }
  }
}

query GetWorkByASINISBN($isbn: String!) {
  editions(
    where: {
      _or: [
        { isbn_10: { _eq: $isbn } }
        { isbn_13: { _eq: $isbn } }
        { asin: { _eq: $isbn } }
      ]
    }
  ) {
    id
    book_id
  }
}

query GetEdition($editionID: Int!) {
  editions_by_pk(id: $editionID) {
    ...EditionInfo
    book {
      ...WorkInfo
    }
  }
}

query GetAuthor($id: Int!) {
  authors_by_pk(id: $id) {
    location
    slug
  }
}

query GetAuthorEditions($id: Int!, $limit: Int!, $offset: Int!) {
  authors_by_pk(id: $id) {
    ...AuthorInfo
    contributions(
      limit: $limit
      offset: $offset
      order_by: { book: { ratings_count: desc } }
      where: {
        contributable_type: { _eq: "Book" }
        book: { book_status_id: { _eq: "1" } }
      }
    ) {
      ...Contributions

      book {
        id
        title
        ratings_count
        ...DefaultEditions
      }
    }
  }
}

query Search($query: String!) {
  search(
    query: $query
    per_page: 15
    query_type: "book"
    fields: "title,isbns,series_names,author_names,alternative_titles"
    weights: "5,1,3,5,1"
    sort: "ratings_count:desc,_text_match:desc"
  ) {
    ids
  }
}

query GetSeries($seriesID: Int!, $limit: Int!, $offset: Int!) {
  series_by_pk(id: $seriesID) {
    id
    name
    description
    books_count

    book_series(
      limit: $limit
      offset: $offset
      where: { book: { book_status_id: { _eq: "1" } } }
      order_by: [{ position: asc }, { book: { users_read_count: desc } }]
    ) {
      book_id
      details
      position
      featured
    }
  }
}

query GetRecommended($from: date!, $to: date!, $limit: Int!, $offset: Int!) {
  books_trending(from: $from, to: $to, limit: $limit, offset: $offset) {
    workIDs: ids
  }
}
